dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=processortrace
    - RUSTFLAGS='-D warnings'

matrix:
  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu DISABLE_TESTS=1
      rust: nightly
    # OSX
    - env: TARGET=x86_64-apple-darwin DISABLE_TESTS=1
      os: osx
      rust: nightly

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true
  - rustup component add rustfmt-preview --toolchain nightly

script:
  - bash ci/script.sh
  - cargo +nightly fmt --version
  - cargo +nightly fmt --package processortrace -- --check

after_script: set +e

branches:
  except:
    - staging.tmp
    - trying.tmp

notifications:
  email:
    on_success: never
